// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TriaYazarKasaRestApi.Data.Acces.Data;

#nullable disable

namespace TriaYazarKasaRestApi.Data.Acces.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260414141238_RenamePaymentsJsonToSaleJson")]
    partial class RenamePaymentsJsonToSaleJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("TriaYazarKasaRestApi.Data.Acces.Models.BekoBasketOperationRecord", b =>
                {
                    b.Property<string>("BasketId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReceiptNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiptResultJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaleJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uuid")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ZNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("BasketId");

                    b.ToTable("BekoBasketOperations");
                });

            modelBuilder.Entity("TriaYazarKasaRestApi.Data.Acces.Models.HuginOperationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HuginOperationLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
